-- Create a table for unique visitors
create table if not exists visitors (
  id uuid default gen_random_uuid() primary key,
  visitor_id text not null unique, -- This will be a cookie or local storage ID
  ip_address text,
  country text,
  city text,
  region text,
  user_agent text,
  device_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_visit timestamp with time zone default timezone('utc'::text, now()) not null,
  visit_count integer default 1
);

-- Create a table for page views
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  visitor_id text not null references visitors(visitor_id) on delete cascade,
  url text not null,
  referrer text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create indexes for performance
create index if not exists idx_visitors_visitor_id on visitors(visitor_id);
create index if not exists idx_page_views_visitor_id on page_views(visitor_id);
create index if not exists idx_page_views_created_at on page_views(created_at);

-- Enable Row Level Security (RLS)
alter table visitors enable row level security;
alter table page_views enable row level security;

-- Create policies
-- Allow service_role to do everything (default)

-- Allow public insert to visitors (if using client-side tracking, but we use server-side API now)
-- However, for the API route to work with service_role, we don't strictly need public policies if we use admin client.
-- But if we want to allow potential client-side reads or writes:
create policy "Allow public insert to visitors"
  on visitors for insert
  with check (true);

create policy "Allow public insert to page_views"
  on page_views for insert
  with check (true);

-- Allow authenticated users (admins) to view data
create policy "Allow authenticated read visitors"
  on visitors for select
  using (auth.role() = 'authenticated');

create policy "Allow authenticated read page_views"
  on page_views for select
  using (auth.role() = 'authenticated');

-- RPC for fetching analytics stats (Optional, used if you want to aggregate on DB side)
create or replace function get_analytics_stats()
returns json
language plpgsql
security definer
as $$
declare
  total_visitors int;
  total_page_views int;
  visitors_by_country json;
  top_pages json;
begin
  select count(*) into total_visitors from visitors;
  select count(*) into total_page_views from page_views;
  
  select json_agg(t) into visitors_by_country from (
    select country, count(*) as count
    from visitors
    where country is not null
    group by country
    order by count desc
    limit 10
  ) t;

  select json_agg(t) into top_pages from (
    select url as path, count(*) as count
    from page_views
    group by url
    order by count desc
    limit 10
  ) t;

  return json_build_object(
    'total_visitors', total_visitors,
    'total_page_views', total_page_views,
    'visitors_by_country', coalesce(visitors_by_country, '[]'::json),
    'top_pages', coalesce(top_pages, '[]'::json)
  );
end;
$$;
