export const regionsInGhana = [
  "AHAFO",
  "ASHANTI",
  "BONO EAST",
  "BRONG AHAFO",
  "CENTRAL",
  "EASTERN",
  "GREATER ACCRA",
  "NORTH EAST",
  "NORTHERN",
  "OTI",
  "SAVANNAH",
  "UPPER EAST",
  "UPPER WEST",
  "VOLTA",
  "WESTERN",
  "WESTERN NORTH",
] as const;

export const shippingFeeByRegion: { [key: string]: number } = {
  ASHANTI: 0,
  "BONO EAST": 0,
  "BRONG AHAFO": 0,
  CENTRAL: 0,
  EASTERN: 0,
  "GREATER ACCRA": 20,
  "NORTH EAST": 0,
  NORTHERN: 0,
  OTI: 0,
  SAVANNAH: 0,
  "UPPER EAST": 0,
  "UPPER WEST": 0,
  VOLTA: 0,
  WESTERN: 0,
  "WESTERN NORTH": 0,
};
