import {
  IconBrandWechat,
  IconCalculator,
  IconFileAnalytics,
  IconFileInvoice,
  IconGauge,
  IconMail,
  IconReceipt,
  IconSettings2,
  IconShoppingCart,
  IconStars,
  IconTicket,
  IconUser,
  IconUserCog,
  IconUserShield,
  IconUsersGroup,
} from "@tabler/icons-react";
import { Dashboard } from "../Pages/Dashboard";
import { Orders } from "../Pages/Orders";
import { IAdminNavItems } from "@/types";
import { AdminUsers } from "../Pages/AdminUsers";
import { UserPermission } from "@/types/roles";
import { Services } from "../Pages/Services";
import MyAccount from "../Pages/MyAccount";
import { PriceCalculator } from "../PriceCalculator";

export const adminNavItems: IAdminNavItems[] = [
  {
    value: "services",
    label: "Services",
    icon: <IconSettings2 />,
    isVisible: true,
    component: <Services />,
    requiredPermission: UserPermission.ADMIN_PERMISSIONS,
  },
  {
    value: "dashboard",
    label: "Dashboard",
    icon: <IconGauge />,
    isVisible: true,
    component: <Dashboard />,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "customers",
    label: "Customers",
    icon: <IconUsersGroup />,
    isVisible: true,
    component: <>Customers</>,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "orders",
    label: "Orders",
    icon: <IconShoppingCart />,
    isVisible: true,
    component: <Orders />,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "reviews",
    label: "Reviews",
    icon: <IconStars />,
    isVisible: false,
    component: <>Reviews</>,
    requiredPermission: UserPermission.MANAGER_PERMISSIONS,
  },
  {
    value: "messages",
    label: "Messages",
    icon: <IconMail />,
    isVisible: true,
    component: <>Messages</>,
    requiredPermission: UserPermission.MANAGER_PERMISSIONS,
  },
  {
    value: "chat",
    label: "Chat",
    icon: <IconBrandWechat />,
    isVisible: false,
    component: <>Chat</>,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "discount-coupons",
    label: "Discount & Coupons",
    icon: <IconTicket />,
    isVisible: false,
    component: <>Discount & Coupons</>,
    requiredPermission: UserPermission.ADMIN_PERMISSIONS,
  },
  {
    value: "invoices",
    label: "Invoices",
    icon: <IconFileInvoice />,
    isVisible: false,
    component: <>Invoices</>,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "receipts",
    label: "Receipts",
    icon: <IconReceipt />,
    isVisible: false,
    component: <>Receipts</>,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  {
    value: "reports",
    label: "Reports",
    icon: <IconFileAnalytics />,
    isVisible: false,
    component: <>Reports</>,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
  "divider",
  {
    value: "employees",
    label: "Employees",
    icon: <IconUser />,
    isVisible: true,
    component: <>Employees</>,
    requiredPermission: UserPermission.MANAGER_PERMISSIONS,
  },
  {
    value: "new-admin-user",
    label: "Admin Users",
    icon: <IconUserShield />,
    isVisible: true,
    component: <AdminUsers />,
    requiredPermission: UserPermission.ADMIN_PERMISSIONS,
  },
  "divider",
  {
    value: "price-calculator",
    label: "Price Calculator",
    icon: <IconCalculator />,
    isVisible: true,
    component: <PriceCalculator />,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },

  "divider",
  {
    value: "my-account",
    label: "My Account",
    icon: <IconUserCog />,
    isVisible: true,
    component: <MyAccount />,
    requiredPermission: UserPermission.SALES_REP_PERMISSIONS,
  },
];
