name: Deploy to Dev

on:
  push:
    branches:
      - dev # Trigger on push to dev branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Netlify Dev
        run: netlify deploy --dir=./out --site=$NETLIFY_DEV_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod

    env:
      NETLIFY_DEV_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
