name: Push from Dev to Main

on:
  push:
    branches:
      - dev
  workflow_dispatch: # Enable manual triggers

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge dev into main
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git checkout main
          git merge dev --no-ff -m "Merge dev into main"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
